# !!!!!!!!! NOTE !!!!!!!!!!!
# pass-through variables from environment into containers with ${VAR}
# start services with ./start.sh script
---
version: '2'
services:
    devops:
      build: .
      entrypoint: |
        bash -c "
        tail -f /dev/null"
      volumes:
        - .:/app
