# JDBC Sink Connector for Confluent Platform docs: https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html

name=PGS
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=io.confluent.connect.avro.AvroConverter
topics=users
connection.url=jdbc:postgresql://db:5432/postgres
connection.user=postgres
connection.password=open
dialect.name=PostgreSqlDatabaseDialect
insert.mode=upsert
batch.size=1
pk.mode=record_key
pk.fields=id
auto.create=true
auto.evolve=true


# connection docs: https://docs.confluent.io/current/schema-registry/connect.html
# replace values!!!!
value.converter.schema.registry.url=https://${SCHEMA_REGISTRY_ENDPOINT}
value.converter.basic.auth.credentials.source=USER_INFO
value.converter.basic.auth.user.info=${SCHEMA_REGISTRY_KEY}:${SCHEMA_REGISTRY_SECRET}
