#!/bin/sh
set -x

export SIMPLE_SETTINGS=kafka_faker.settings

PYTHONPATH=kafka_faker faust -A app worker --with-web --web-port=$WORKER_PORT --loglevel=info
#PYTHONPATH=kafka_faker faust -A app agents
